# Generated by Django 3.2.2 on 2021-05-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carna_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="Person's first name")),
                ('last_name', models.CharField(max_length=30, verbose_name="Person's last name")),
                ('bio', models.TextField(verbose_name='Tell me about yourself')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
