# Generated by Django 3.2.2 on 2021-05-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carna_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarnaUser',
        ),
    ]
